# These are supported funding model platforms

github: 
  - Code2With-Pratik
  - Swift-Coder-Pratik
patreon: PratikPatreon
open_collective: PratikCollective
ko_fi: PratikKoFi
tidelift: npm/pratik-package
community_bridge: cloud-foundry
liberapay: pratik-liberapay
issuehunt: pratik-issuehunt
lfx_crowdfunding: cloud-foundry
polar: pratik-polar
buy_me_a_coffee: pratik-coffee
thanks_dev: pratik-thanks
custom: 
  - https://example.com/sponsor1
  - https://example.com/sponsor2
